### ISSUE TITLE
Error: Invalid semver value provided: [object Object]<br> &nbsp; &nbsp;at /var/www/dev/node_modules/express-semver-routing/index.js:26:46

### ISSUE THREAD

**Issue by ChristopherWalz** [n-johnson/express-semver-routing#1]
```
app.put('/matches/:id/', version('>= 1.0.5'), authUser, function (req, res) {
});
```

`curl -X PUT -H "Accept-Version: 1.0.3" foo.bar/matches/123`

results in

`Error: Invalid semver value provided: [object Object]<br> &nbsp; &nbsp;at /var/www/dev/node_modules/express-semver-routing/index.js:26:46<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/dev/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/var/www/dev/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/dev/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /var/www/dev/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at param (/var/www/dev/node_modules/express/lib/router/index.js:349:14)<br> &nbsp; &nbsp;at param (/var/www/dev/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/var/www/dev/node_modules/express/lib/router/index.js:410:3)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:121:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at authAPI (/var/www/dev/app.js:49:10)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/var/www/dev/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)<br> &nbsp; &nbsp;at next (/var/www/dev/node_modules/express/lib/router/route.js:125:14)`

**Comment by n-johnson** [comment]
It looks like you defined `version` with: `var version = require('express-semver-routing')` - however it should be defined like `var version = require('express-semver-routing')();` Notice the extra function call in the later case. Calling the module as a function makes it possible to pass in an optional config object.

Thanks for the report - I've added an additional check to catch this in most cases, and the module will now throw a more helpful error on startup as opposed to at the time of a request. I will be pushing the update shortly - but in the meantime adding `()` should fix the issue you're seeing. Let me know if it doesn't!

**Comment by ChristopherWalz** [comment]
Thank you! Works as expected now!
